name: Boxpub
url: http://sivy.github.io/boxpub
description: Personal Publishing from Dropbox

permalink: /:year/:month/:day/:title
paginate: 10
pygments: true

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
